### ISSUE TITLE
 Weapon identification problem

### ISSUE THREAD

**Issue by Aleax2016** [BlackChaplin/Apex-AimAssist-NoRecoil-2023#3]
If the first weapon is a weapon with a golden sight (submachine gun), then press "2" to switch the secondary weapon, the voice recognition cannot be recognized, and the recoil will jump randomly (meaning that the secondary weapon is not recognized). I have not encountered this problem at the shooting range. But encountered in the match

**Comment by Aleax2016** [comment]
Then press 1 to recognize the submachine gun by voice, but press 2 not to recognize the sub-weapon, only weapon 1.

**Comment by Aleax2016** [comment]
Press 2 to stop announcing weapons

**Comment by BlackChaplin** [comment]
> If the first weapon is a weapon with a golden sight (submachine gun), then press "2" to switch the secondary weapon, the voice recognition cannot be recognized, and the recoil will jump randomly (meaning that the secondary weapon is not recognized). I have not encountered this problem at the shooting range. But encountered in the match

My fault. I have another keyboard key assigned to switch weapons, and while I was testing the program, I removed the action when pressing the 2nd keyboard button. Therefore, when clicked, the weapon recognition script did not start. In the future I want to add functionality for reassigning keys so that such problems do not arise.
Here is the corrected file. Test and report back please
[apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13619153/apexmaster.zip)
